### ISSUE TITLE
Failed to find post key

### ISSUE THREAD

**Issue by pokiaJH** [Redcxx/Pikax#3]
it show that:
GET: https://accounts.pixiv.net/login? with params: None >>> Reason: HTTPSConnectionPool(host='accounts.pixiv.net', port=443): Max retries exceeded with url: /login (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003999898>, 'Connection to accounts.pixiv.net timed out. (connect timeout=10)'))
 !!! GET failed: https://accounts.pixiv.net/login? params: None

**Comment by Redcxx** [comment]
params: None in dicates that there isn't any paramter passed along with the login.
I guess that you attempted login without username and password perhaps?
Could you please show me how did you login?

Thanks

**Comment by Redcxx** [comment]
I added a proxies variable in [settings.py](https://github.com/Redcxx/Pikax/blob/master/pikax/settings.py#L35) which is used when sending requests

**Comment by Redcxx** [comment]
.... emmm I assume it solved your problem
