### ISSUE TITLE
为什么即使输入正确的用户名和密码，依然显示密码错误

### ISSUE THREAD

**Issue by husicbasic** [Redcxx/Pikax#4]
在网页上是可以登入的，但是每次运行之后就变成了这样

pikax.exceptions.UserError: Failed to login, please check your username and password

**Comment by Redcxx** [comment]
P站反爬估计又升级了，搞了一阵没找到原因，估计要再摸索一阵。。。qwq

**Comment by Redcxx** [comment]
我用跑的时候没有遇到你的问题，能的话请提供相关代码

关于你这个问题的一些信息：
这个UserError是当你用用户名和密码创建一个User对象的时候抛出的，既然没有抛出登录异常的话就说明其实已经登录了，接着程序会想办法用你登录的session搞到你的用户id，如果失败就会抛出这个异常。

**Comment by husicbasic** [comment]
> 我用跑的时候没有遇到你的问题，能的话请提供相关代码
> 
> 关于你这个问题的一些信息：
> 这个UserError是当你用用户名和密码创建一个User对象的时候抛出的，既然没有抛出登录异常的话就说明其实已经登录了，接着程序会想办法用你登录的session搞到你的用户id，如果失败就会抛出这个异常。

我也没有用别的代码，就是demo里面的
from pikax.pikax import Pikax, settings
pixiv = Pikax()
pixiv.login(settings.username, settings.password)  # 不必要但强烈推荐
results = pixiv.rank(limit=20, content='illust', type='daily', mode='safe')
pixiv.download(results, folder='#Pixiv_daily_ranking')




 Login: ******
 Sending request to retrieve post key ...
 GET: https://accounts.pixiv.net/login? with params: None 200
 Post key successfully retrieved: c62177277b78c22e8d6bdd4fe6f9d10d
 Sending request to attempt login ...
 POST: https://accounts.pixiv.net/api/login?lang=en with params: None 200
 >>> Login request successfully sent to Pixiv as [****]
 GET: https://www.pixiv.net/touch/ajax/user/self/status with params: None 200
Traceback (most recent call last):
  File "D:/PythonLearning/untitled1/test1.py", line 4, in <module>
    pixiv.login(settings.username, settings.password)  # 不必要但强烈推荐
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\site-packages\pikax\pikax.py", line 132, in login
    self.user = User(username=username, password=password)
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\site-packages\pikax\items.py", line 292, in __init__
    raise UserError('Failed to login, please check your username and password')
pikax.exceptions.UserError: Failed to login, please check your username and password

**Comment by Redcxx** [comment]
唔。。，我刚刚更新了版本修复了一些bug，也尝试修复了一下你的问题，你能更新后再试试吗

p.s. 如果只是想要排行榜上的插画的话你可以不登录直接用，不会损失的

**Comment by husicbasic** [comment]
更新了一下，不登陆确实没问题，但是不能下R18的就很难受，反正还是很感谢了

**Comment by Redcxx** [comment]
能麻烦你登陆P站之后在浏览器新窗口打开[https://www.pixiv.net/touch/ajax/user/self/status](https://www.pixiv.net/touch/ajax/user/self/status)看看嘛？如果登陆了会有你的id之类的信息，没登录的话东西比较少。我有空会再找找原因的，不过我现在没办法复现所以比较麻烦。。

**Comment by Redcxx** [comment]
现在登陆失败会让你把cookies给它然后重试登陆。如果你想登陆的话现在你需要在浏览器登陆之后把cookies复制下来然后回到命令行粘贴回车。你可以试试，我自己试了可行

**Comment by Redcxx** [comment]
已在v2.0.0中修复
