### ISSUE TITLE
 Login with local cookies failed &Failed login with cookies entered

### ISSUE THREAD

**Issue by Rosonlee** [Redcxx/Pikax#6]
第一次用，碰到的这个问题，
用户名跟密码用settings里面的初始值和自己的都不可以，使用安卓的话会最后使用默认用户登陆，然后提示'NoneType' object has no attribute 'bookmarks'

**Comment by Redcxx** [comment]
唔。。我试了下没遇到你的问题。。请问你是在国内吗，这个项目不提供vpn支持的

**Comment by Rosonlee** [comment]
对的，我挂着ss访问的，但是不登录只爬首页可以访问哎，只有登陆账户功能不可以

**Comment by Redcxx** [comment]
对的那是因为排行榜什么的不需要登录就可以访问，麻烦能提供复现的步骤吗。

**Comment by Rosonlee** [comment]
这个样子
```python
from pikax.pikax import Pikax, settings

pixiv = Pikax()
user = pixiv.login(username=settings.username, password=settings.password)
bookmarks = user.bookmarks(limit=20)  
pixiv.download(bookmarks)  
```
---
  Attempting Login
 Attempting Web Login ...
 Post key successfully retrieved: **************************
 Sending requests to attempt login ...
 Login request sent to Pixiv
 Login with local cookies failed, would you like to provide a new cookies?
 [y] Yesss!
 [n] Noooo! (Attempt alternate login with username and password)
 [=] Please select an option:
y
 [=] Please enter your cookies here, just php session id will work,
 [=] e.g. PHPSESSIONID=1234567890:>? PHPSESSIONID=*********
 Failed login with cookies entered, would you like to try again? [y/n]
 [=] Please select an option:

**Comment by Redcxx** [comment]
额我在本地试了还是可以。。错误的PHPSESSIONID才会出现了你描述的错误。。（摸脑袋。。）emmmm因为得到的ID我是直接以`=`分开然后就传入请求了。。要不你再查查ID是不是对的？不行的话我目前也没什么好办法了。。。抱歉技术有限qwq

**Comment by Redcxx** [comment]
不过你可以尝试不用ID登录，因为选`n`的话会用另一种登录方式也是可以的

**Comment by Rosonlee** [comment]
嗯嗯我看一下哦，不过安卓方式登陆是这样的
` android login failed: POST failed: https://oauth.secure.pixiv.net/auth/token params: None
 >>> failed login, using default client, some features will be unavailable`

**Comment by Redcxx** [comment]
我也不清楚了。。真的抱歉。。有空的话我再详细查一下吧。。我太菜了qwq

**Comment by Rosonlee** [comment]
嗯嗯，没有事情，辛苦你了哦
